ux_icons:
  # The local directory where icons are stored.
  icon_dir: "%kernel.project_dir%/assets/icons"

  # Default attributes to add to all icons.
  default_icon_attributes:
    # Default:
    fill: currentColor

  # Configuration for the "on demand" icons powered by Iconify.design.
  iconify:
    enabled: true

    # Whether to use the "on demand" icons powered by Iconify.design.
    on_demand: true

    # The endpoint for the Iconify API.
    endpoint: "https://api.iconify.design"
